name: slgnara_collar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  image_picker: ^1.1.2
  shared_preferences: ^2.3.5
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.5
  video_player: ^2.9.5
  app_links: ^7.0.0
  firebase_app_check: ^0.3.2+10
  google_sign_in: ^6.2.2
  cached_network_image: ^3.4.1
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
