// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaioq00snJ_JiEuq2peKvbxwlruSPHN5g',
    appId: '1:190818522498:web:dcf1ecab7352171a7beb9b',
    messagingSenderId: '190818522498',
    projectId: 'hunters-heart',
    authDomain: 'hunters-heart.firebaseapp.com',
    storageBucket: 'hunters-heart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp3QtjPp9D8QBsRevNp0RbT789bb34nIQ',
    appId: '1:190818522498:android:5848f182ee623f347beb9b',
    messagingSenderId: '190818522498',
    projectId: 'hunters-heart',
    storageBucket: 'hunters-heart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxf9G8YS9rNJX_5mDMS7HRMYzsmvfd5BQ',
    appId: '1:190818522498:ios:286b0309515a86bb7beb9b',
    messagingSenderId: '190818522498',
    projectId: 'hunters-heart',
    storageBucket: 'hunters-heart.firebasestorage.app',
    iosBundleId: 'com.signaracollar.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxf9G8YS9rNJX_5mDMS7HRMYzsmvfd5BQ',
    appId: '1:190818522498:ios:286b0309515a86bb7beb9b',
    messagingSenderId: '190818522498',
    projectId: 'hunters-heart',
    storageBucket: 'hunters-heart.firebasestorage.app',
    iosBundleId: 'com.signaracollar.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaioq00snJ_JiEuq2peKvbxwlruSPHN5g',
    appId: '1:190818522498:web:7a0a20967e15b1f87beb9b',
    messagingSenderId: '190818522498',
    projectId: 'hunters-heart',
    authDomain: 'hunters-heart.firebaseapp.com',
    storageBucket: 'hunters-heart.firebasestorage.app',
  );
}
